export interface Inputs {
  zone_id: string;
  name: string;
  comment: string;
  mail: string;
  job: string;
  visibility: boolean;
  actualisation: boolean;
  organisme_id: number;
  categorie_id: number;
  service: number;
  address: string;
  city: string;
  zipcode: number;
  phone: number;
  website: string;
  pmr: boolean;
  animals: boolean;
  description: string;
  infos_alerte: string;
  schedule_id_1: string | null;
  schedule_id_2: string | null;
  schedule_id_3: string | null;
  schedule_id_4: string | null;
  schedule_id_5: string | null;
  schedule_id_6: string | null;
  schedule_id_7: string | null;
  schedule_openam_1: string;
  schedule_openam_2: string;
  schedule_openam_3: string;
  schedule_openam_4: string;
  schedule_openam_5: string;
  schedule_openam_6: string;
  schedule_openam_7: string;
  schedule_closeam_1: string;
  schedule_closeam_2: string;
  schedule_closeam_3: string;
  schedule_closeam_4: string;
  schedule_closeam_5: string;
  schedule_closeam_6: string;
  schedule_closeam_7: string;
  schedule_openpm_1: string;
  schedule_openpm_2: string;
  schedule_openpm_3: string;
  schedule_openpm_4: string;
  schedule_openpm_5: string;
  schedule_openpm_6: string;
  schedule_openpm_7: string;
  schedule_closepm_1: string;
  schedule_closepm_2: string;
  schedule_closepm_3: string;
  schedule_closepm_4: string;
  schedule_closepm_5: string;
  schedule_closepm_6: string;
  schedule_closepm_7: string;
  [key: string]: string | number | boolean | null;
}
