export const orga = {
  id: 1,
  name: "PÔLE D'ACCUEIL, D'INFORMATION, D'ORIENTATION (PAIO)",
  address: '66 bis avenue Étienne-Billières',
  city: 'Toulouse',
  zipcode: '31000',
  phone: null,
  mail: null,
  website: null,
  pmr: true,
  animals: false,
  description:
    "Écoute, renseignement et orientation pour les personnes sans domicile fixe n’ayant pas de référent social. Service social public qui apporte une aide ponctuelle sur les besoins de première nécessité et l'accès aux droits. Pour assurer un suivi, une orientation vers un référent social aura lieu.",
  infos_alertes:
    "Fermeture le troisième dimanche de la quatrième année du calendrier maya postcolonial si y'a pas grève à la SNCF",
  hours: [
    {
      day: 1,
      name: 'Lundi',
      open_am: '09h00',
      close_am: '12h00',
      open_pm: '14h00',
      close_pm: '17h00',
    },
    {
      day: 2,
      name: 'Mardi',
      open_am: '09h00',
      close_am: '12h00',
      open_pm: '14h00',
      close_pm: '17h00',
    },
    {
      day: 3,
      name: 'Mercredi',
      open_am: '09h00',
      close_am: '12h00',
      open_pm: '14h00',
      close_pm: '17h00',
    },
    {
      day: 4,
      name: 'Jeudi',
      open_am: '09h00',
      close_am: '12h00',
      open_pm: '14h00',
      close_pm: '17h00',
    },
    {
      day: 5,
      name: 'Vendredi',
      open_am: '09h00',
      close_am: '12h00',
      open_pm: '14h00',
      close_pm: '17h00',
    },
    {
      day: 6,
      name: 'Samedi',
      open_am: '09h00',
      close_am: '12h00',
      open_pm: '14h00',
      close_pm: '17h00',
    },
    {
      day: 7,
      name: 'Dimanche',
      open_am: '09h00',
      close_am: '12h00',
      open_pm: '14h00',
      close_pm: '17h00',
    },
  ],
  contacts: [
    {
      id: 5,
      name: 'Contact principal',
      job: null,
      phone: '0645789865',
      mail: 'Stephane.CAZEAUX@mairie-toulouse.fr',
      visibility: 'private',
      actualisation: true,
    },
    {
      id: 6,
      name: 'FRAIR Lucie ',
      job: 'Meuf méga importante',
      phone: null,
      mail: 'lucie.frair@mairie-toulouse.fr',
      visibility: 'public',
      actualisation: false,
    },
    {
      id: 7,
      name: 'MALGOUYRES Alexandra',
      job: 'assistance social',
      phone: '0345986578',
      mail: 'ALEXANDRA.MALGOUYRES@mairie-toulouse.fr',
      visibility: 'private',
      actualisation: false,
    },
    {
      id: 8,
      name: 'QUINTARD Emilie',
      job: null,
      phone: '0645783245',
      mail: 'Emilie.QUINTARD@mairie-toulouse.fr',
      visibility: 'public',
      actualisation: true,
    },
  ],
  services: [
    {
      id: 1,
      name: 'Permanence sociale',
      description:
        "Possibilité de rendez-vous avec un travailleur social en semaine l'après-midi.\nPermanence sociale du PAIO (par ordre d'arrivée) ",
      infos_alerte: 'Fermé le huitième dimanche du quizinème mois',
      categories: 'Manger',
      contacts: [
        {
          id: 5,
          name: 'Contact principal',
          job: null,
          phone: '0645789865',
          mail: 'Stephane.CAZEAUX@mairie-toulouse.fr',
          visibility: 'private',
          actualisation: true,
        },
      ],
      hours: [
        {
          day: 1,
          name: 'Lundi',
          open_am: '09h00',
          close_am: '12h00',
          open_pm: '14h00',
          close_pm: '17h00',
        },
        {
          day: 2,
          name: 'Mardi',
          open_am: '09h00',
          close_am: '12h00',
          open_pm: '14h00',
          close_pm: '17h00',
        },
        {
          day: 3,
          name: 'Mercredi',
          open_am: '09h00',
          close_am: '12h00',
          open_pm: '14h00',
          close_pm: '17h00',
        },
        {
          day: 4,
          name: 'Jeudi',
          open_am: '09h00',
          close_am: '12h00',
          open_pm: '14h00',
          close_pm: '17h00',
        },
        {
          day: 5,
          name: 'Vendredi',
          open_am: '09h00',
          close_am: '12h00',
          open_pm: '14h00',
          close_pm: '17h00',
        },
        {
          day: 6,
          name: 'Samedi',
          open_am: '09h00',
          close_am: '12h00',
          open_pm: '14h00',
          close_pm: '17h00',
        },
        {
          day: 7,
          name: 'Dimanche',
          open_am: '09h00',
          close_am: '12h00',
          open_pm: '14h00',
          close_pm: '17h00',
        },
      ],
    },
    {
      id: 2,
      name: 'Accueil de jour',
      description:
        "Possibilité de rendez-vous avec un travailleur social en semaine l'après-midi.\nPermanence sociale du PAIO (par ordre d'arrivée) ",
      infos_alerte: 'Fermé le huitième dimanche du quizinème mois',
      categories: 'Manger',
      contacts: [
        {
          id: 5,
          name: 'Contact principal',
          job: null,
          phone: '0645789865',
          mail: 'Stephane.CAZEAUX@mairie-toulouse.fr',
          visibility: 'private',
          actualisation: true,
        },
      ],
      hours: [
        {
          day: 1,
          name: 'Lundi',
          open_am: '09h00',
          close_am: '12h00',
          open_pm: '14h00',
          close_pm: '17h00',
        },
        {
          day: 2,
          name: 'Mardi',
          open_am: '09h00',
          close_am: '12h00',
          open_pm: '14h00',
          close_pm: '17h00',
        },
        {
          day: 3,
          name: 'Mercredi',
          open_am: '09h00',
          close_am: '12h00',
          open_pm: '14h00',
          close_pm: '17h00',
        },
        {
          day: 4,
          name: 'Jeudi',
          open_am: '09h00',
          close_am: '12h00',
          open_pm: '14h00',
          close_pm: '17h00',
        },
        {
          day: 5,
          name: 'Vendredi',
          open_am: '09h00',
          close_am: '12h00',
          open_pm: '14h00',
          close_pm: '17h00',
        },
        {
          day: 6,
          name: 'Samedi',
          open_am: '09h00',
          close_am: '12h00',
          open_pm: '14h00',
          close_pm: '17h00',
        },
        {
          day: 7,
          name: 'Dimanche',
          open_am: '09h00',
          close_am: '12h00',
          open_pm: '14h00',
          close_pm: '17h00',
        },
      ],
    },
  ],
};
